version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
  db:
    image: postgres
  app:
    build: .
    command: sh -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
    links:
      - redis
  redis:
    image: redis:latest
    command: sh -c "redis-server"
  celery:
    build: .
    volumes:
      - .:/code
    command: celery -A simple_project worker -l info
    depends_on:
      - redis